sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: GodDai的博客
name: GodDai
#description: Minimalism is a jekyll theme for minimalist
copyright_time: 2020
avatar: https://s1.ax1x.com/2020/06/18/Nm8fzD.jpg

github: https://github.com/goddai
rss: true

#theme: jekyll-theme-minimalism
remote_theme: showzeng/Minimalism

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
